kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-pvc-clone-pvc
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: demo-storageclass
  dataSource:
    name: demo-pvc-file-system
    kind: PersistentVolumeClaim
